#include "text.hpp"
// Standard Libraries
#include <iostream>
// Program headers
#include <utility>
#include "window.hpp"
#include "RAIIWrapper.hpp"
#include "utils/data.hpp"
#include "utils/matrix.hpp"
// FreeType Library
#include <ft2build.h>
#include FT_FREETYPE_H



textRenderEngine::textRenderEngine(window& win, const char* fontPath) : m_window{win} {

   if (FT_Init_FreeType(&m_library)) std::cout << "Could not init FreeType" << std::endl;

   // Shader program specifically for drawing text
   m_shaderProgramText = createShaderProgram("../src/shaders/text_vertex.glsl", "../src/shaders/text_fragment.glsl");

   // Create VAO and VBO for a quad with 2D position and UV
   glGenVertexArrays(1, &m_vao);
   glGenBuffers(1, &m_vbo);
   GLScopedVAO tempVAO(m_vao);
   GLScopedVBO tempVBO(m_vbo);
   // 2 position floats and 2 UV floats
   glEnableVertexAttribArray(0);
   glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 4 * sizeof(float), 0);
   glEnableVertexAttribArray(1);
   glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 4 * sizeof(float), (void*)(2 * sizeof(float)));
   // 6 vertices
   glBufferData(GL_ARRAY_BUFFER, sizeof(float) * 6 * 4, nullptr, GL_DYNAMIC_DRAW);



   //---------------------- LOAD AND MAP FONT FACE ----------------------
   // Create new freetype font from file
   if (FT_New_Face(m_library, fontPath, 0, &m_fontFace)) std::cout << "Failed to load font" << std::endl;
   FT_Set_Pixel_Sizes(m_fontFace, 0, 16);

   // Set pixel unpack alignment to 1 byte (glyph bitmaps are tightly packed, not 4-byte aligned)
   GLScopedUnpackAlignment tempAlignment(1);

   // ASCII 32–127: printable characters
   for (unsigned char c = 32; c < 128; c++)
   {
      // Will return non-zero if failed
      if (FT_Load_Char(m_fontFace, c, FT_LOAD_RENDER)) continue;

      // Create an OpenGL texture and fill it with the character bitmap generated by "FT_Load_Char"
      GLuint texture;
      glGenTextures(1, &texture);
      GLScopedTexture2D tempTexture(texture);
      glTexImage2D(GL_TEXTURE_2D,0,GL_RED,m_fontFace->glyph->bitmap.width,m_fontFace->glyph->bitmap.rows,0,GL_RED,GL_UNSIGNED_BYTE,m_fontFace->glyph->bitmap.buffer);

      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
      glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

      // Create a character grouping the: texture, size of texture, ...
      // bearing - how far from the top-left (theoretical pen position) the character will be drawn, and ...
      // advance - how much to move to the right before drawing next character
      character character = {
         texture,
         vec2(m_fontFace->glyph->bitmap.width, m_fontFace->glyph->bitmap.rows),
         vec2(m_fontFace->glyph->bitmap_left, m_fontFace->glyph->bitmap_top),
         static_cast<int>(m_fontFace->glyph->advance.x)
      };

      // Map the byte of the character to the character struct to lookup textures later
      m_characters.insert(std::make_pair(c, character));
   }
}



textRenderEngine::~textRenderEngine(){
   // Clear font face from memory
   FT_Done_Face(m_fontFace);
   // Clear character textures from memory
   for (auto& [c, ch] : m_characters){
       glDeleteTextures(1, &ch.textureID);
   }
   m_characters.clear();

   // Delete OpenGL resources and clear freetype library
   glDeleteBuffers(1, &m_vbo);
   glDeleteVertexArrays(1, &m_vao);
   FT_Done_FreeType(m_library);
}



void textRenderEngine::RenderText(std::string text, float x, float y, Color col){

   // Convert hex color to normalized RGB (0–1 range)
   vec3 color = hexColorToFloat(col).xyz();

   // Bind window FBO to draw to and set viewport to match
   GLScopedFBO tempFBO(m_window.fbo);
   GLScopedViewport tempViewPort(0, 0, m_window.fboWidth, m_window.fboHeight);

   GLScopedVAO tempVAO(m_vao);
   GLScopedVBO tempVBO(m_vbo);
   GLScopedProgram tempProgram(m_shaderProgramText);

   // Enable blending for transparency around the character
   GLScopedCapability tempBlendEnable(GL_BLEND, true);
   GLScopedBlendFunc tempBlendMode(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

   // Send texture and text color to GPU
   GLScopedActiveTexture tempActiveTex(GL_TEXTURE0);
   glUniform1i(glGetUniformLocation(m_shaderProgramText, "charTexture"), 0);
   glUniform3fv(glGetUniformLocation(m_shaderProgramText, "textColor"),1,&color[0]);

   for (char c : text){

      // Make sure there is a character in the font face for this character
      if (m_characters.find(c) == m_characters.end()) continue;
      const character& ch = m_characters[c];

      float xpos = x + ch.bearing[0];
      float ypos = m_window.fboHeight - y - ch.bearing[1]; // Convert to top-left origin
      float w = ch.size[0];
      float h = ch.size[1];

      // Convert pixel positions to NDC coordinates of the quad (NDC is bewteen -1 and 1)
      float xmin = (2*(xpos)   / m_window.fboWidth ) -1;
      float xmax = (2*(xpos+w) / m_window.fboWidth ) -1;
      float ymin = (2*(ypos)   / m_window.fboHeight) -1;
      float ymax = (2*(ypos+h) / m_window.fboHeight) -1;

      // Generate 2 triangles (quad) with position (NDC) and UV coordinates
      m_vertices = {
         xmin, ymax,   0.0f, 0.0f,
         xmin, ymin,   0.0f, 1.0f,
         xmax, ymin,   1.0f, 1.0f,

         xmin, ymax,   0.0f, 0.0f,
         xmax, ymin,   1.0f, 1.0f,
         xmax, ymax,   1.0f, 0.0f
      };

      // Pass character texture and new VBO vertices to the shader and draw the quad
      GLScopedTexture2D tempTexture(ch.textureID);
      glBufferSubData(GL_ARRAY_BUFFER, 0, m_vertices.size()* sizeof(GLfloat), m_vertices.data());
      glDrawArrays(GL_TRIANGLES, 0, 6);

      // Convert from 26.6 fixed point format to float (pixels)
      x += (ch.advance >> 6);
   }
}
